# Generated by Django 5.2 on 2025-04-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_fund_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='serial_number',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
